"""add naming realationship

Revision ID: 0bcfcceb773b
Revises: 
Create Date: 2024-10-09 08:07:32.999095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcfcceb773b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.String(length=50), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('status_event', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('user_password', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name'),
    sa.UniqueConstraint('user_password')
    )
    op.create_table('events_users',
    sa.Column('events_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['events_id'], ['events.id'], name='fk_event_users_id'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='fk_event_users_id'),
    sa.PrimaryKeyConstraint('events_id', 'users_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events_users')
    op.drop_table('users')
    op.drop_table('events')
    # ### end Alembic commands ###
